### ISSUE TITLE
Add advance / expense : the coast field display an incoherent error message

### ISSUE THREAD

**Issue by nilscox** [Bopzor/expenses#2]
Oy oy matey!

On the add expense (or advance) forms, the coast field displays an incoherent error message.

*Steps to reproduce*

- open the app
- click on the "coast" field
- input "5,."

*Expected behavior*

The other fields display an error message sayin' like "this is not a number" or so.

*Actual behavior*

The `coast` field displays an error message saying that the field is required.

*Version information*

Galaxy A3, Android 8. Please don't ask if you don't need more information.

**Comment by Bopzor** [comment]
Thanks !

Because an `input[type=number]` value is empty if it is not a number, my validation failed (condition form empty string matched).

I change the error message to `This field is required and must be a number` :).
